name: Deploy Vendure
on:
  push:
    branches:
      - develop
      - main

env:
  GCLOUD_PROJECT: gcloud-aktivierung

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2.1.1
        with:
          project_id: gcloud-aktivierung
          credentials_json: ${{ secrets.GCLOUD_DEVOPS_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: gcloud-aktivierung
      - name: Build Docker container
        run: ./build-docker.sh gcloud-aktivierung

  deploy-production:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploying Prod ${{ matrix.instances.name }} with ${{ matrix.instances.secret }}
    needs: [ build ]
    strategy:
      matrix:
        instances: [
          { name: "gcloud-aktivierung-api", db: "prod-db", secret: "ENV_PROD", memory: "2G"},
          { name: "gcloud-aktivierung-worker", db: "prod-db", secret: "ENV_PROD", memory: "2G"},
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2.1.1
        with:
          project_id: gcloud-aktivierung
          credentials_json: ${{ secrets.GCLOUD_DEVOPS_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: gcloud-aktivierung
      - run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets[matrix.instances.secret]}}
      - run: ./deploy.sh ${{ matrix.instances.name }} ${{ matrix.instances.db }} ${{ matrix.instances.memory }}

  deploy-test:
    if: ${{ github.ref == 'refs/heads/develop' }}
    name: Deploying Test ${{ matrix.instances.name }} with ${{ matrix.instances.secret }}
    needs: [ build ]
    strategy:
      matrix:
        instances: [
          { name: "gcloud-aktivierung-test-api", db: "test-db", secret: "ENV_TEST", memory: "1G"},
          { name: "gcloud-aktivierung-test-worker", db: "test-db", secret: "ENV_TEST", memory: "1G"},
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2.1.1
        with:
          project_id: gcloud-aktivierung
          credentials_json: ${{ secrets.GCLOUD_DEVOPS_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: gcloud-aktivierung
      - run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets[matrix.instances.secret]}}
      - run: ./deploy.sh ${{ matrix.instances.name }} ${{ matrix.instances.db }} ${{ matrix.instances.memory }} gcloud-aktivierung